version: '3'

services:

  app:  
    image: nextcloud
    restart: always
    ports:
      - 8085:80
    volumes:
      - nextcloud:/var/www/html
      - data:/var/www/html/data

volumes:
  nextcloud:
  data:

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.21.0.0/16



