version: '3'

services:

  proxy:
    build: ./nginx-proxy
    restart: unless-stopped
    ports:
      - 8085:80
      - 8443:443
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - ./nginx-proxy/conf.d:/etc/nginx/conf.d
    networks:
      - proxy-tier
    depends_on:
      - omgwtfssl

  omgwtfssl:
    build: ./omgwtfssl
    restart: "no"
    volumes:
      - certs:/certs
    environment:
      - SSL_SUBJECT=servhostname.local
      - CA_SUBJECT=my@example.com
      - SSL_KEY=/certs/servhostname.local.key
      - SSL_CSR=/certs/servhostname.local.csr
      - SSL_CERT=/certs/servhostname.local.crt
    networks:
      - proxy-tier

  db:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - postgres.env

  redis:
    image: redis
    restart: always

  app:  
    build: ./app
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - data:/var/www/html/data
    env_file:
      - postgres.env
    depends_on:
      - db
      - redis

  web:
    image: nginx
    restart: always
    volumes:
      - nextcloud:/var/www/html:ro
      - ./web/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - VIRTUAL_HOST=servhostname.local
    depends_on:
      - app
      - proxy
    networks:
      - proxy-tier
      - default

  cron:
    build: ./app
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - data:/var/www/html/data
    user: www-data
    entrypoint: |
      bash -c 'bash -s <<EOF
        trap "break;exit" SIGHUP SIGINT SIGTERM
        while [ ! -f /var/www/html/config/config.php ]; do
          sleep 1
        done
        while true; do
          php -f /var/www/html/cron.php
          sleep 15m
        done
      EOF'
    depends_on:
      - db
      - redis

volumes:
  nextcloud:
  data:
  db:
  certs:
  vhost.d:
  html:

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.21.0.0/16
  proxy-tier:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.22.0.0/16


